language: java
jdk: oraclejdk8
services:
  - docker
script: mvn install
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=latest
  - export IMAGE_NAME=martinhuszti/analisebme
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: analisebme
  skip_cleanup: true
