language: java
jdk: oraclejdk8
services:
  - docker
script: mvn clean install
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=latest
  - export IMAGE_NAME=martinhuszti/analisebme
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME